# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Normalização Textual de CGU
tagline:          'Um normalizador textual para o português brasileiro'
description:      'Ferramentas e recursos para normalização textual de conteúdo gerado por usuário'
url:              thalesbertaglia.com
baseurl:          /enelvo

author:
  name:           'Thales Bertaglia'
  url:            thalesbertaglia.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           github.com/tfcbertaglia
